#!/usr/bin/env python
# Testing purposes only

import rospy
import sys

from road_crossing.srv import start_algorithm


def start_client(start=True, stop=False):
    rospy.wait_for_service('start_algorithm')
    try:
        start_cli = rospy.ServiceProxy('start_algorithm', start_algorithm)
        resp1 = start_cli(start, stop)
        return resp1.is_running
    except rospy.ServiceException as e:
        print("Service call failed: %s"%e)


if __name__ == "__main__":
    if (len(sys.argv) != 2):
        print("Usage: start.py <start/stop>")
        exit()
    if (sys.argv[1] == "start"):
        start = True
        stop = False
        print("Requesting start")
    elif (sys.argv[1] == "stop"):
        start = False
        stop = True
        print("Requesting stop")
    else:
        print("Invalid argument")
        exit()
    print("Start successful: %s"%start_client(start, stop))

